/**
 * @generated by scripts/architecture-sync.mjs — do not edit.
 *
 * Measured from the tree, so the map's numbers cannot drift from the code.
 * `UNCLAIMED` is what no module on the map covers: run the sync script, then
 * either give an existing module a wider pattern in coverage.json or add the
 * node the repo has been missing.
 */

export const MEASURED: Record<string, { count: number; loc: number }> = {
  'auth': { count: 1, loc: 163 },
  'balances': { count: 3, loc: 213 },
  'client': { count: 1, loc: 90 },
  'cron': { count: 1, loc: 41 },
  'expensesRpc': { count: 4, loc: 577 },
  'expensesSvc': { count: 1, loc: 177 },
  'home': { count: 3, loc: 537 },
  'join': { count: 2, loc: 237 },
  'kit': { count: 5, loc: 154 },
  'login': { count: 3, loc: 345 },
  'membership': { count: 4, loc: 317 },
  'model': { count: 3, loc: 226 },
  'ocrPipeline': { count: 2, loc: 127 },
  'project': { count: 2, loc: 782 },
  'projectsSvc': { count: 1, loc: 117 },
  'quick': { count: 1, loc: 273 },
  'scanner': { count: 2, loc: 348 },
  'schema': { count: 1, loc: 189 },
  'shell': { count: 2, loc: 123 },
  'split': { count: 1, loc: 140 },
}

export const UNCLAIMED: string[] = []
